// Generated by `npx supabase gen types typescript --project-id undeyznqkmnhgdetpbdk`.
// Regenerate after new migrations are applied to the hosted project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      allowed_emails: {
        Row: {
          auto_whitelisted: boolean
          created_at: string
          email: string
          role: string
        }
        Insert: {
          auto_whitelisted?: boolean
          created_at?: string
          email: string
          role?: string
        }
        Update: {
          auto_whitelisted?: boolean
          created_at?: string
          email?: string
          role?: string
        }
        Relationships: []
      }
      boardgame_ideas: {
        Row: {
          created_at: number
          id: string
          notes: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          id: string
          notes?: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          id?: string
          notes?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
      book_ideas: {
        Row: {
          created_at: number
          id: string
          notes: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          id: string
          notes?: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          id?: string
          notes?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
      climb_sessions: {
        Row: {
          created_at: number
          date: string
          discipline: string
          id: string
          location: string
          notes: string | null
        }
        Insert: {
          created_at: number
          date: string
          discipline: string
          id: string
          location: string
          notes?: string | null
        }
        Update: {
          created_at?: number
          date?: string
          discipline?: string
          id?: string
          location?: string
          notes?: string | null
        }
        Relationships: []
      }
      climbs: {
        Row: {
          created_at: number
          date: string
          discipline: string
          grade: string
          id: string
          sent: boolean
          session_id: string
        }
        Insert: {
          created_at: number
          date: string
          discipline: string
          grade: string
          id: string
          sent?: boolean
          session_id: string
        }
        Update: {
          created_at?: number
          date?: string
          discipline?: string
          grade?: string
          id?: string
          sent?: boolean
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "climbs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "climb_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      habit_checks: {
        Row: {
          created_at: number
          day: string
          habit_id: string
          id: string
        }
        Insert: {
          created_at: number
          day: string
          habit_id: string
          id: string
        }
        Update: {
          created_at?: number
          day?: string
          habit_id?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "habit_checks_habit_id_fkey"
            columns: ["habit_id"]
            isOneToOne: false
            referencedRelation: "habits"
            referencedColumns: ["id"]
          },
        ]
      }
      habits: {
        Row: {
          archived_at: number | null
          created_at: number
          emoji: string
          id: string
          name: string
        }
        Insert: {
          archived_at?: number | null
          created_at: number
          emoji: string
          id: string
          name: string
        }
        Update: {
          archived_at?: number | null
          created_at?: number
          emoji?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      project_members: {
        Row: {
          created_at: string
          email: string
          project_id: string
        }
        Insert: {
          created_at?: string
          email: string
          project_id: string
        }
        Update: {
          created_at?: string
          email?: string
          project_id?: string
        }
        Relationships: []
      }
      shop_area_members: {
        Row: {
          area_id: string
          created_at: string
          email: string
        }
        Insert: {
          area_id: string
          created_at?: string
          email: string
        }
        Update: {
          area_id?: string
          created_at?: string
          email?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_area_members_area_id_fkey"
            columns: ["area_id"]
            isOneToOne: false
            referencedRelation: "shop_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_areas: {
        Row: {
          created_at: number
          id: string
          name: string
          share_token: string
        }
        Insert: {
          created_at?: number
          id?: string
          name: string
          share_token?: string
        }
        Update: {
          created_at?: number
          id?: string
          name?: string
          share_token?: string
        }
        Relationships: []
      }
      shop_items: {
        Row: {
          area_id: string
          created_at: number
          done: boolean
          id: string
          text: string
          updated_at: number
        }
        Insert: {
          area_id: string
          created_at: number
          done?: boolean
          id: string
          text: string
          updated_at: number
        }
        Update: {
          area_id?: string
          created_at?: number
          done?: boolean
          id?: string
          text?: string
          updated_at?: number
        }
        Relationships: [
          {
            foreignKeyName: "shop_items_area_fk"
            columns: ["area_id"]
            isOneToOne: false
            referencedRelation: "shop_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      todos: {
        Row: {
          created_at: number
          done: boolean
          id: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          done?: boolean
          id: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          done?: boolean
          id?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      area_share_token: { Args: { aid: string }; Returns: string }
      can_access_area: { Args: { aid: string }; Returns: boolean }
      get_invite: { Args: { token: string }; Returns: string }
      is_member: { Args: { pid: string }; Returns: boolean }
      is_owner: { Args: never; Returns: boolean }
      join_area: { Args: { token: string }; Returns: undefined }
      jwt_email: { Args: never; Returns: string }
      redeem_invite: {
        Args: { guest_email: string; token: string }
        Returns: undefined
      }
      revoke_area_guest: {
        Args: { aid: string; guest_email: string }
        Returns: string
      }
      rotate_area_token: { Args: { aid: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
