// Generated by: npm run db:types
// Regenerate after applying new migrations to the hosted project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      allowed_emails: {
        Row: {
          auto_whitelisted: boolean
          created_at: string
          email: string
          role: string
        }
        Insert: {
          auto_whitelisted?: boolean
          created_at?: string
          email: string
          role?: string
        }
        Update: {
          auto_whitelisted?: boolean
          created_at?: string
          email?: string
          role?: string
        }
        Relationships: []
      }
      boardgame_ideas: {
        Row: {
          created_at: number
          id: string
          notes: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          id: string
          notes?: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          id?: string
          notes?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
      book_ideas: {
        Row: {
          created_at: number
          id: string
          notes: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          id: string
          notes?: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          id?: string
          notes?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
      climb_sessions: {
        Row: {
          created_at: number
          date: string
          discipline: string
          id: string
          location: string
          notes: string | null
        }
        Insert: {
          created_at: number
          date: string
          discipline: string
          id: string
          location: string
          notes?: string | null
        }
        Update: {
          created_at?: number
          date?: string
          discipline?: string
          id?: string
          location?: string
          notes?: string | null
        }
        Relationships: []
      }
      climbs: {
        Row: {
          created_at: number
          date: string
          discipline: string
          grade: string
          id: string
          sent: boolean
          session_id: string
        }
        Insert: {
          created_at: number
          date: string
          discipline: string
          grade: string
          id: string
          sent?: boolean
          session_id: string
        }
        Update: {
          created_at?: number
          date?: string
          discipline?: string
          grade?: string
          id?: string
          sent?: boolean
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "climbs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "climb_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      custom_events: {
        Row: {
          all_day: boolean
          category: string
          city: string
          created_at: number
          end_at: string | null
          id: string
          image: string | null
          note: string
          start_at: string
          title: string
          updated_at: number
          url: string
          venue: string | null
        }
        Insert: {
          all_day?: boolean
          category?: string
          city?: string
          created_at: number
          end_at?: string | null
          id: string
          image?: string | null
          note?: string
          start_at: string
          title: string
          updated_at: number
          url?: string
          venue?: string | null
        }
        Update: {
          all_day?: boolean
          category?: string
          city?: string
          created_at?: number
          end_at?: string | null
          id?: string
          image?: string | null
          note?: string
          start_at?: string
          title?: string
          updated_at?: number
          url?: string
          venue?: string | null
        }
        Relationships: []
      }
      event_marks: {
        Row: {
          event: Json
          id: string
          state: string
          updated_at: number
        }
        Insert: {
          event: Json
          id: string
          state: string
          updated_at: number
        }
        Update: {
          event?: Json
          id?: string
          state?: string
          updated_at?: number
        }
        Relationships: []
      }
      event_prefs: {
        Row: {
          favourite_categories: string[]
          id: string
          updated_at: number
        }
        Insert: {
          favourite_categories?: string[]
          id?: string
          updated_at: number
        }
        Update: {
          favourite_categories?: string[]
          id?: string
          updated_at?: number
        }
        Relationships: []
      }
      habit_checks: {
        Row: {
          created_at: number
          day: string
          habit_id: string
          id: string
        }
        Insert: {
          created_at: number
          day: string
          habit_id: string
          id: string
        }
        Update: {
          created_at?: number
          day?: string
          habit_id?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "habit_checks_habit_id_fkey"
            columns: ["habit_id"]
            isOneToOne: false
            referencedRelation: "habits"
            referencedColumns: ["id"]
          },
        ]
      }
      habits: {
        Row: {
          archived_at: number | null
          created_at: number
          emoji: string
          id: string
          name: string
        }
        Insert: {
          archived_at?: number | null
          created_at: number
          emoji: string
          id: string
          name: string
        }
        Update: {
          archived_at?: number | null
          created_at?: number
          emoji?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      life_entries: {
        Row: {
          created_at: number
          day: string
          id: string
          kind: string
          ref: string
          updated_at: number
          value: Json
          week: string
        }
        Insert: {
          created_at: number
          day: string
          id: string
          kind: string
          ref: string
          updated_at: number
          value?: Json
          week: string
        }
        Update: {
          created_at?: number
          day?: string
          id?: string
          kind?: string
          ref?: string
          updated_at?: number
          value?: Json
          week?: string
        }
        Relationships: []
      }
      life_weeks: {
        Row: {
          id: string
          imported_at: number
          plan: Json
          updated_at: number
          week: string
        }
        Insert: {
          id: string
          imported_at: number
          plan: Json
          updated_at: number
          week: string
        }
        Update: {
          id?: string
          imported_at?: number
          plan?: Json
          updated_at?: number
          week?: string
        }
        Relationships: []
      }
      links: {
        Row: {
          created_at: number
          id: string
          notes: string
          read: boolean
          tags: string[]
          title: string
          updated_at: number
          url: string
        }
        Insert: {
          created_at: number
          id: string
          notes?: string
          read?: boolean
          tags?: string[]
          title?: string
          updated_at: number
          url: string
        }
        Update: {
          created_at?: number
          id?: string
          notes?: string
          read?: boolean
          tags?: string[]
          title?: string
          updated_at?: number
          url?: string
        }
        Relationships: []
      }
      meal_entries: {
        Row: {
          carbs_g: number | null
          created_at: number
          day: string
          estimated: boolean
          fat_g: number | null
          grams: number | null
          id: string
          kcal: number | null
          meal: string
          protein_g: number | null
          text: string
          updated_at: number
          weighed: boolean
        }
        Insert: {
          carbs_g?: number | null
          created_at: number
          day: string
          estimated?: boolean
          fat_g?: number | null
          grams?: number | null
          id: string
          kcal?: number | null
          meal: string
          protein_g?: number | null
          text: string
          updated_at: number
          weighed?: boolean
        }
        Update: {
          carbs_g?: number | null
          created_at?: number
          day?: string
          estimated?: boolean
          fat_g?: number | null
          grams?: number | null
          id?: string
          kcal?: number | null
          meal?: string
          protein_g?: number | null
          text?: string
          updated_at?: number
          weighed?: boolean
        }
        Relationships: []
      }
      project_invites: {
        Row: {
          created_at: string
          project_id: string
          share_token: string
        }
        Insert: {
          created_at?: string
          project_id: string
          share_token?: string
        }
        Update: {
          created_at?: string
          project_id?: string
          share_token?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_invites_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: true
            referencedRelation: "shareable_projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_members: {
        Row: {
          created_at: string
          email: string
          project_id: string
        }
        Insert: {
          created_at?: string
          email: string
          project_id: string
        }
        Update: {
          created_at?: string
          email?: string
          project_id?: string
        }
        Relationships: []
      }
      project_prefs: {
        Row: {
          hidden: boolean | null
          id: string
          starred: boolean
          updated_at: number
          user_id: string
        }
        Insert: {
          hidden?: boolean | null
          id: string
          starred?: boolean
          updated_at: number
          user_id?: string
        }
        Update: {
          hidden?: boolean | null
          id?: string
          starred?: boolean
          updated_at?: number
          user_id?: string
        }
        Relationships: []
      }
      shareable_projects: {
        Row: {
          id: string
        }
        Insert: {
          id: string
        }
        Update: {
          id?: string
        }
        Relationships: []
      }
      shop_area_members: {
        Row: {
          area_id: string
          created_at: string
          email: string
        }
        Insert: {
          area_id: string
          created_at?: string
          email: string
        }
        Update: {
          area_id?: string
          created_at?: string
          email?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_area_members_area_id_fkey"
            columns: ["area_id"]
            isOneToOne: false
            referencedRelation: "shop_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_area_tokens: {
        Row: {
          area_id: string
          created_at: string
          share_token: string
        }
        Insert: {
          area_id: string
          created_at?: string
          share_token?: string
        }
        Update: {
          area_id?: string
          created_at?: string
          share_token?: string
        }
        Relationships: [
          {
            foreignKeyName: "shop_area_tokens_area_id_fkey"
            columns: ["area_id"]
            isOneToOne: true
            referencedRelation: "shop_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      shop_areas: {
        Row: {
          created_at: number
          id: string
          name: string
        }
        Insert: {
          created_at?: number
          id?: string
          name: string
        }
        Update: {
          created_at?: number
          id?: string
          name?: string
        }
        Relationships: []
      }
      shop_items: {
        Row: {
          area_id: string
          created_at: number
          done: boolean
          id: string
          text: string
          updated_at: number
        }
        Insert: {
          area_id: string
          created_at: number
          done?: boolean
          id: string
          text: string
          updated_at: number
        }
        Update: {
          area_id?: string
          created_at?: number
          done?: boolean
          id?: string
          text?: string
          updated_at?: number
        }
        Relationships: [
          {
            foreignKeyName: "shop_items_area_fk"
            columns: ["area_id"]
            isOneToOne: false
            referencedRelation: "shop_areas"
            referencedColumns: ["id"]
          },
        ]
      }
      todos: {
        Row: {
          created_at: number
          done: boolean
          id: string
          text: string
          updated_at: number
        }
        Insert: {
          created_at: number
          done?: boolean
          id: string
          text: string
          updated_at: number
        }
        Update: {
          created_at?: number
          done?: boolean
          id?: string
          text?: string
          updated_at?: number
        }
        Relationships: []
      }
      trip_companions: {
        Row: {
          created_at: number
          emoji: string
          id: string
          name: string
          updated_at: number
        }
        Insert: {
          created_at: number
          emoji?: string
          id: string
          name: string
          updated_at: number
        }
        Update: {
          created_at?: number
          emoji?: string
          id?: string
          name?: string
          updated_at?: number
        }
        Relationships: []
      }
      trip_ideas: {
        Row: {
          companion_ids: string[]
          created_at: number
          done: boolean
          id: string
          notes: string
          title: string
          updated_at: number
        }
        Insert: {
          companion_ids?: string[]
          created_at: number
          done?: boolean
          id: string
          notes?: string
          title: string
          updated_at: number
        }
        Update: {
          companion_ids?: string[]
          created_at?: number
          done?: boolean
          id?: string
          notes?: string
          title?: string
          updated_at?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      area_share_token: { Args: { aid: string }; Returns: string }
      can_access_area: { Args: { aid: string }; Returns: boolean }
      event_categories_valid: { Args: { cats: string[] }; Returns: boolean }
      get_invite: { Args: { token: string }; Returns: string }
      get_project_invite: { Args: { token: string }; Returns: string }
      is_member: { Args: { pid: string }; Returns: boolean }
      is_owner: { Args: never; Returns: boolean }
      join_area: { Args: { token: string }; Returns: undefined }
      join_project: { Args: { token: string }; Returns: string }
      jwt_email: { Args: never; Returns: string }
      links_tags_within_length: { Args: { tags: string[] }; Returns: boolean }
      project_invite_token: { Args: { pid: string }; Returns: string }
      redeem_invite: {
        Args: { guest_email: string; token: string }
        Returns: undefined
      }
      redeem_project_invite: {
        Args: { guest_email: string; token: string }
        Returns: string
      }
      revoke_area_guest: {
        Args: { aid: string; guest_email: string }
        Returns: string
      }
      revoke_project_guest: {
        Args: { guest_email: string; pid: string }
        Returns: string
      }
      rotate_area_token: { Args: { aid: string }; Returns: string }
      rotate_project_invite: { Args: { pid: string }; Returns: string }
      trips_ids_within_length: { Args: { ids: string[] }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
