// Regenerates src/lib/database.types.ts from the linked hosted project.
// Writes a temp file first and only replaces the real file on success, so
// a failed run (paused project, no network, not logged in) never truncates it.
//
//   npm run db:types
import { spawnSync } from 'node:child_process'
import { renameSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'src', 'lib', 'database.types.ts')
const HEADER =
  '// Generated by: npm run db:types\n' +
  '// Regenerate after applying new migrations to the hosted project.\n\n'

const res = spawnSync('npx', ['supabase', 'gen', 'types', 'typescript', '--linked'], {
  cwd: root,
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
  stdio: ['inherit', 'pipe', 'inherit'],
})

if (res.error || res.status !== 0 || !res.stdout.trim()) {
  console.error(`db:types failed (${res.error?.message ?? `exit ${res.status}`}); ${target} left untouched.`)
  process.exit(1)
}

// Temp file next to the target (same filesystem, so the rename is atomic).
const tmp = `${target}.tmp`
try {
  writeFileSync(tmp, HEADER + res.stdout)
  renameSync(tmp, target)
} catch (err) {
  rmSync(tmp, { force: true })
  console.error(`db:types could not write the file: ${err.message}; ${target} left untouched.`)
  process.exit(1)
}
console.log(`Wrote ${target}`)
