#!/usr/bin/env node
// Stamps out the files for a new dashboard subproject, automating steps 4-6
// of docs/NEW_PROJECT.md (the sync wrapper, the SQL migration, the page). The
// remaining steps (registry entry, route, db.ts edits) touch files that
// already exist and are too fragile to rewrite generically, so this script
// prints them as paste-ready TODOs instead of editing anything.
//
// Usage: npm run new-project -- <id> [--synced] [--name <Name>] [--emoji <emoji>]
// (the "--" is required so npm forwards the flags instead of eating them)

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

function usage() {
  console.log(`Usage: npm run new-project -- <id> [--synced] [--name <Name>] [--emoji <emoji>]

  IMPORTANT: the "--" before <id> is required. Without it, npm itself
  swallows "--synced"/"--name"/"--emoji" as (unknown) npm config flags
  instead of passing them to this script — you'll silently get a local-only
  page with the default 📦 emoji and no error beyond an "npm warn".

  <id>        kebab-case project id, e.g. "reading" (required)
  --synced    also generate a cloud-sync wrapper + SQL migration
  --name      override the derived PascalCase component name (default: derived from <id>)
  --emoji     override the default placeholder emoji (default: 📦)

Generates (never overwrites, never edits an existing file):
  src/projects/<id>/<Name>.tsx
  src/lib/<id>Sync.ts                 (only with --synced)
  supabase/migrations/<timestamp>_<id>.sql   (only with --synced)

Everything else (registry entry, route, db.ts edits) is printed as a
paste-ready TODO list — see docs/NEW_PROJECT.md for the full 7-step recipe
this automates (steps 4-6 are generated, 1/2/3/7 are printed/manual).`)
}

// --- arg parsing -------------------------------------------------------------

function parseArgs(argv) {
  let synced = false
  let name = null
  let emoji = null
  const positional = []
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--synced') {
      synced = true
    } else if (a === '--name') {
      name = argv[++i]
    } else if (a === '--emoji') {
      emoji = argv[++i]
    } else if (a.startsWith('--')) {
      console.error(`error: unknown flag "${a}"`)
      process.exit(1)
    } else {
      positional.push(a)
    }
  }
  return { id: positional[0], synced, name, emoji }
}

// --- naming helpers ----------------------------------------------------------

const KEBAB_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/

function toPascalCase(id) {
  return id
    .split('-')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('')
}

function toCamelCase(id) {
  const p = toPascalCase(id)
  return p[0].toLowerCase() + p.slice(1)
}

// Naive English pluralizer for table/column names derived from the project
// id. Only appends "s" when the word doesn't already look plural — without
// this, an id whose last word is already plural (e.g. "book-ideas",
// "boardgame-ideas") gets double-pluralized ("bookIdeass", "book_ideass").
function pluralize(word) {
  return /s$/i.test(word) ? word : `${word}s`
}

function utcTimestamp() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return (
    `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}` +
    `${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`
  )
}

// --- templates ----------------------------------------------------------------

function pageTemplateLocal({ id, Name, emoji, thingsCamel }) {
  return `import { useState, type FormEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '../../lib/db'
import { Button } from '../../components/Button'
import { PageHeader } from '../../components/PageHeader'
import { EmptyState } from '../../components/EmptyState'

// Generated by scripts/new-project.mjs from the pattern in src/projects/todo/Todo.tsx.
// Local-only for now: this page works fully offline against Dexie, no sync.
//
// This row shape is a placeholder. Once you're happy with it, move it into
// src/lib/db.ts as a real typed table (docs/NEW_PROJECT.md step 3) and swap
// the \`db.table('${thingsCamel}')\` calls below for \`db.${thingsCamel}\` — until
// then this file stays self-contained and type-checks without touching db.ts.
interface ${Name}Item {
  id: string
  text: string
  createdAt: number
  updatedAt: number
}

const table = () => db.table<${Name}Item, string>('${thingsCamel}')

export function ${Name}() {
  const [text, setText] = useState('')
  const items = useLiveQuery(() => table().orderBy('createdAt').toArray())

  async function addItem(e: FormEvent) {
    e.preventDefault()
    const trimmed = text.trim()
    if (!trimmed) return
    const now = Date.now()
    await table().put({ id: crypto.randomUUID(), text: trimmed, createdAt: now, updatedAt: now })
    setText('')
  }

  async function remove(id: string) {
    await table().delete(id)
  }

  return (
    <div>
      <PageHeader
        emoji="${emoji}"
        title="${Name}"
        subtitle="Saved on this device."
      />

      <form onSubmit={(e) => void addItem(e)} className="mb-6 flex gap-2">
        <input
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Add something…"
          autoComplete="off"
          enterKeyHint="done"
          className="min-h-10 w-full rounded-lg border border-slate-700 bg-slate-800 px-3.5 text-sm placeholder:text-slate-500 focus:border-indigo-400 focus:outline-none"
        />
        <Button type="submit" disabled={!text.trim()}>
          Add
        </Button>
      </form>

      {items === undefined ? null : items.length === 0 ? (
        <EmptyState
          emoji="🌤️"
          title="Nothing yet"
          hint="Items you add are saved on this device and work offline."
        />
      ) : (
        <ul className="space-y-2">
          {items.map((item) => (
            <li key={item.id} className="flex items-stretch gap-2">
              <div className="flex min-h-12 w-full min-w-0 flex-1 items-center gap-3 rounded-lg border border-slate-800 bg-slate-800/50 px-4">
                <span className="min-w-0 flex-1 truncate">{item.text}</span>
              </div>
              <Button
                variant="danger"
                onClick={() => void remove(item.id)}
                aria-label={\`Delete \${item.text}\`}
                className="min-w-10"
              >
                ✕
              </Button>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
`
}

function pageTemplateSynced({ id, Name, emoji, thingsCamel }) {
  return `import { useState, type FormEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '../../lib/db'
import { add${Name}, delete${Name}, sync, type ${Name}Item } from '../../lib/${toCamelCase(id)}Sync'
import { Button } from '../../components/Button'
import { PageHeader } from '../../components/PageHeader'
import { EmptyState } from '../../components/EmptyState'
import { SyncCard } from '../../components/SyncCard'

// Generated by scripts/new-project.mjs from the pattern in src/projects/todo/Todo.tsx
// + src/lib/todoSync.ts. Local-first: works fully offline/signed-out against
// Dexie; sync is a layer on top (see ../../lib/${toCamelCase(id)}Sync.ts).
//
// The row type lives in ${toCamelCase(id)}Sync.ts as a placeholder. Once you're happy with
// it, move it into src/lib/db.ts as a real typed table (docs/NEW_PROJECT.md
// step 3) and follow the printed TODOs to wire it up for real.

export function ${Name}() {
  const [text, setText] = useState('')
  const items = useLiveQuery(() => db.table<${Name}Item, string>('${thingsCamel}').orderBy('createdAt').toArray())

  async function addItem(e: FormEvent) {
    e.preventDefault()
    const trimmed = text.trim()
    if (!trimmed) return
    await add${Name}(trimmed)
    setText('')
  }

  async function remove(id: string) {
    await delete${Name}(id)
  }

  return (
    <div>
      <PageHeader
        emoji="${emoji}"
        title="${Name}"
        subtitle="Saved on this device. Sign in to sync across devices."
      />

      <SyncCard sync={sync} />

      <form onSubmit={(e) => void addItem(e)} className="mb-6 flex gap-2">
        <input
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Add something…"
          autoComplete="off"
          enterKeyHint="done"
          className="min-h-10 w-full rounded-lg border border-slate-700 bg-slate-800 px-3.5 text-sm placeholder:text-slate-500 focus:border-indigo-400 focus:outline-none"
        />
        <Button type="submit" disabled={!text.trim()}>
          Add
        </Button>
      </form>

      {items === undefined ? null : items.length === 0 ? (
        <EmptyState
          emoji="🌤️"
          title="Nothing yet"
          hint="Items you add are saved on this device and work offline."
        />
      ) : (
        <ul className="space-y-2">
          {items.map((item) => (
            <li key={item.id} className="flex items-stretch gap-2">
              <div className="flex min-h-12 w-full min-w-0 flex-1 items-center gap-3 rounded-lg border border-slate-800 bg-slate-800/50 px-4">
                <span className="min-w-0 flex-1 truncate">{item.text}</span>
              </div>
              <Button
                variant="danger"
                onClick={() => void remove(item.id)}
                aria-label={\`Delete \${item.text}\`}
                className="min-w-10"
              >
                ✕
              </Button>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
`
}

function syncTemplate({ id, Name, thingsCamel, remoteTable }) {
  return `import { db, type OutboxPayload, type OutboxTable } from './db'
import { createCloudSync, type TableSync } from './cloudSync'
import { useSyncStatus } from './useSyncStatus'

// Generated by scripts/new-project.mjs from the pattern in src/lib/todoSync.ts
// (THE reference integration — see docs/NEW_PROJECT.md). Local-first sync for
// the ${id} project, built on the generic engine in cloudSync.ts.
//
// NOTE: until you complete docs/NEW_PROJECT.md step 3 (move ${Name}Item into
// src/lib/db.ts as a real typed table, and add '${remoteTable}' /
// ${Name}Item to the OutboxTable / OutboxPayload unions there), this file
// can't be *statically* known by the compiler to be one of the sync engine's
// known tables/payloads. The two \`as unknown as\` casts below are scaffolding
// for that gap — delete them once the db.ts edits land, at which point
// '${remoteTable}' and ${Name}Item will satisfy OutboxTable/OutboxPayload for
// real and \`db.table('${thingsCamel}')\` can become \`db.${thingsCamel}\`.

export interface ${Name}Item {
  id: string
  text: string
  createdAt: number
  updatedAt: number
}

interface ${Name}Row {
  id: string
  text: string
  created_at: number
  updated_at: number
}

const REMOTE = '${remoteTable}' as unknown as OutboxTable

const ${thingsCamel}Table: TableSync<${Name}Item, ${Name}Row> = {
  remote: REMOTE,
  table: () => db.table<${Name}Item, string>('${thingsCamel}'),
  columns: 'id, text, created_at, updated_at',
  realtime: true,
  updatedAt: (t) => t.updatedAt,
  toRow: (t) => ({
    id: t.id,
    text: t.text,
    created_at: t.createdAt,
    updated_at: t.updatedAt,
  }),
  fromRow: (r) => ({
    id: r.id,
    text: r.text,
    createdAt: Number(r.created_at),
    updatedAt: Number(r.updated_at),
  }),
}

const engine = createCloudSync({
  projectId: '${id}',
  tables: [${thingsCamel}Table],
})

// --- Local mutations (used by the UI; safe with or without sync) -----------

export async function add${Name}(text: string): Promise<void> {
  const now = Date.now()
  const item: ${Name}Item = {
    id: crypto.randomUUID(),
    text,
    createdAt: now,
    updatedAt: now,
  }
  await engine.upsert(REMOTE, item as unknown as OutboxPayload)
}

export async function delete${Name}(id: string): Promise<void> {
  await engine.remove(REMOTE, id)
}

// --- Sync engine ------------------------------------------------------------

export const flush = engine.flush
export const syncNow = engine.syncNow

/** The sync engine instance — pass to <SyncCard sync={sync} /> for status UI. */
export const sync = engine

/** Bound React hook: this project's live SyncStatus. */
export const useStatus = () => useSyncStatus(engine)

/** Start syncing (call when a session exists). Returns a stop function. */
export const start${Name}Sync = engine.start
`
}

function sqlTemplate({ id, remoteTable }) {
  return `-- ${id}: generated by scripts/new-project.mjs. Columns mirror the Dexie shape
-- in src/lib/db.ts (once you've moved the placeholder type there per
-- docs/NEW_PROJECT.md step 3); timestamps are epoch milliseconds (bigint) to
-- match the client.

create table public.${remoteTable} (
  id uuid primary key,
  text text not null,
  created_at bigint not null,
  updated_at bigint not null
);

alter table public.${remoteTable} enable row level security;

-- One policy for all ops. WITH CHECK on the write side is required so a guest
-- can't insert/update rows for a project she isn't a member of.
create policy "members full access" on public.${remoteTable}
  for all
  using (public.is_member('${id}'))
  with check (public.is_member('${id}'));

-- Realtime, so edits reach other devices live.
alter publication supabase_realtime add table public.${remoteTable};
`
}

// --- manual-step TODO printer -------------------------------------------------

function detectNextDbVersion(dbTsSource) {
  const matches = [...dbTsSource.matchAll(/db\.version\((\d+)\)/g)].map((m) => Number(m[1]))
  const highest = matches.length > 0 ? Math.max(...matches) : 0
  return highest + 1
}

function printTodos({ id, Name, emoji, synced, thingsCamel, remoteTable, nextVersion }) {
  console.log(`
Generated the files that are safe to generate. ${synced ? 3 : 1} manual edit${synced ? 's' : ''} left — existing files are never rewritten automatically (too fragile), so paste these in yourself:

1. Registry entry — src/lib/projects.ts (add to the \`projects\` array):

  {
    id: '${id}',
    name: '${Name}',
    emoji: '${emoji}',
    description: 'One line shown on the home card.',
    path: '/${id}',
    status: 'live',
  },

2. Route${synced ? ' + sync start' : ''} — src/App.tsx:

  import { ${Name} } from './projects/${id}/${Name}'
${synced ? `  import { start${Name}Sync } from './lib/${toCamelCase(id)}Sync'\n` : ''}
  // …inside <Routes> / <Route element={<Layout />}> …
  <Route path="/${id}" element={<${Name} />} />
${
  synced
    ? `
  // …inside the app-wide sync effect's \`stops\` array …
  const stops = [
    startShopSync(),
    startTodoSync(),
    // …
    start${Name}Sync(),   // add this
  ]
`
    : ''
}
3. Dexie table — src/lib/db.ts (three edits):

   a. Row interface (replace the placeholder ${Name}Item type in ${
     synced ? `src/lib/${toCamelCase(id)}Sync.ts` : `src/projects/${id}/${Name}.tsx`
   } with this, then import it from db.ts instead):

  export interface ${Name} {
    id: string
    text: string
    createdAt: number
    updatedAt: number   // bump on every write — enables last-writer-wins
  }
${
  synced
    ? `
   b. Add to the OutboxTable / OutboxPayload unions:

  export type OutboxTable =
    | 'shop_items'
    // …existing…
    | '${remoteTable}'

  export type OutboxPayload =
    | ShopItem
    // …existing…
    | ${Name}
`
    : ''
}
   c. Table declaration + a new db.version(${nextVersion}) (copy the previous
      version's full stores block and add this table — Dexie upgrades are
      append-only, never edit an existing db.version(...) block):

  export const db = new Dexie('dashboard') as Dexie & {
    // …existing…
    ${thingsCamel}: EntityTable<${Name}, 'id'>
  }

  db.version(${nextVersion}).stores({
    // …every existing store, copied from the previous version…
    ${thingsCamel}: 'id, createdAt',
  })

   Once done, in ${synced ? `src/lib/${toCamelCase(id)}Sync.ts` : `src/projects/${id}/${Name}.tsx`}: drop the
   \`${Name}Item\` placeholder interface for the real \`${Name}\` import from
   './db'${synced ? ", remove the two `as unknown as` casts, and swap `table: () => db.table('" + thingsCamel + "')` for `table: () => db." + thingsCamel + "`" : ", and swap `db.table('" + thingsCamel + "')` for `db." + thingsCamel + "`"}.

Then: run \`npm run build\`.${synced ? '\nOwner runs `npx supabase db push` to apply the migration (workers never do this).' : ''}
`)
}

// --- main ---------------------------------------------------------------------

function main() {
  const { id, synced, name, emoji: emojiArg } = parseArgs(process.argv.slice(2))

  if (!id) {
    usage()
    process.exit(1)
  }

  if (!KEBAB_RE.test(id)) {
    console.error(`error: "${id}" is not kebab-case (expected e.g. "reading", "meal-planner")`)
    process.exit(1)
  }

  const projectDir = join(ROOT, 'src', 'projects', id)
  if (existsSync(projectDir)) {
    console.error(`error: src/projects/${id} already exists`)
    process.exit(1)
  }

  const Name = name || toPascalCase(id)
  const emoji = emojiArg || '📦'
  const thingsCamel = pluralize(toCamelCase(id))
  const remoteTable = pluralize(id.replace(/-/g, '_'))

  mkdirSync(projectDir, { recursive: true })
  const pagePath = join(projectDir, `${Name}.tsx`)
  writeFileSync(
    pagePath,
    synced
      ? pageTemplateSynced({ id, Name, emoji, thingsCamel })
      : pageTemplateLocal({ id, Name, emoji, thingsCamel }),
  )
  console.log(`created ${pagePath.replace(ROOT + '/', '')}`)

  let syncPath = null
  let sqlPath = null
  if (synced) {
    syncPath = join(ROOT, 'src', 'lib', `${toCamelCase(id)}Sync.ts`)
    if (existsSync(syncPath)) {
      console.error(`error: src/lib/${toCamelCase(id)}Sync.ts already exists`)
      process.exit(1)
    }
    writeFileSync(syncPath, syncTemplate({ id, Name, thingsCamel, remoteTable }))
    console.log(`created ${syncPath.replace(ROOT + '/', '')}`)

    const migrationsDir = join(ROOT, 'supabase', 'migrations')
    mkdirSync(migrationsDir, { recursive: true })
    sqlPath = join(migrationsDir, `${utcTimestamp()}_${id}.sql`)
    writeFileSync(sqlPath, sqlTemplate({ id, remoteTable }))
    console.log(`created ${sqlPath.replace(ROOT + '/', '')}`)
  }

  const dbTsPath = join(ROOT, 'src', 'lib', 'db.ts')
  const nextVersion = detectNextDbVersion(readFileSync(dbTsPath, 'utf8'))

  printTodos({ id, Name, emoji, synced, thingsCamel, remoteTable, nextVersion })
}

main()
