// Subcategories: a finer split of the four big categories (theatre, concerts,
// exhibitions, talks). Optional on an event and conservative on purpose: an
// event that no rule recognises has NO subcategory (never a guess, no "altro"
// bucket). Other categories never get one. The ids are published in
// events.json (`subcategory`), the app mirrors the SUBCATEGORIES map for its
// chips — keep the two in sync and add ids only (docs/EVENTS.md).
//
// Rules are tried in tiers, the title alone first, then title + summary, then
// the source's own character (Mart is an art museum…); inside a tier the
// order of the list is the priority. Keyword syntax is the one of tags.ts
// ('word', 'prefix*', multi-word phrases; accents and punctuation ignored).
// The long description is never read: it name-drops every genre.
import type { Event } from './types.ts'
import type { CategoryId } from './tags.ts'
import { compile, hayOf } from './tags.ts'

export interface Subcategory {
  /** lowercase-kebab slug, published in events.json */
  id: string
  label: string
}

/** Category → its subcategories, in display order. Categories not listed here have none. */
export const SUBCATEGORIES: Partial<Record<CategoryId, Subcategory[]>> = {
  theatre: [
    { id: 'prosa', label: 'Prosa' },
    { id: 'stand-up', label: 'Stand-up e cabaret' },
    { id: 'danza', label: 'Danza' },
    { id: 'musical-opera', label: 'Musical e opera' },
    { id: 'ragazzi', label: 'Teatro ragazzi' },
  ],
  concerts: [
    { id: 'classica', label: 'Classica' },
    { id: 'jazz-blues', label: 'Jazz e blues' },
    { id: 'rock-pop', label: 'Rock e pop' },
    { id: 'folk-cori', label: 'Folk e cori' },
    { id: 'elettronica', label: 'Elettronica' },
  ],
  exhibitions: [
    { id: 'arte', label: 'Arte' },
    { id: 'fotografia', label: 'Fotografia' },
    { id: 'storia', label: 'Storia' },
    { id: 'scienza', label: 'Scienza' },
  ],
  talks: [
    { id: 'conferenze', label: 'Conferenze' },
    { id: 'libri', label: 'Libri' },
    { id: 'dibattiti', label: 'Dibattiti' },
  ],
}

interface Rule {
  id: string
  /** Matched against the title only. */
  head: string[]
  /** Matched against title + summary. */
  short?: string[]
  /** A hit in the title + summary cancels this rule. */
  unless?: string[]
  /** Adapter ids whose events fall here when nothing else decided. */
  sources?: string[]
  /** Any event carrying the `kids` tag wins this rule before the keywords are read. */
  kids?: boolean
}

const RULES: Partial<Record<CategoryId, Rule[]>> = {
  theatre: [
    {
      id: 'ragazzi',
      kids: true,
      head: ['teatro ragazzi', 'teatro per ragazzi', 'teatro famiglie', 'burattin*', 'marionett*', 'teatro d ombre'],
      short: ['teatro ragazzi', 'teatro per ragazzi', 'spettacolo per bambini', 'spettacolo per famiglie', 'burattin*'],
    },
    {
      id: 'musical-opera',
      head: ['musical', 'operetta', 'opera lirica', 'opera buffa', 'stagione lirica', 'melodramma', 'opera e balletto'],
      short: [
        'musical',
        'operetta',
        'opera lirica',
        'opera buffa',
        'melodramma',
        'libretto',
        'donizetti',
        'rossini',
        'puccini',
        'bellini',
      ],
    },
    {
      id: 'danza',
      head: [
        'danza',
        'danze',
        'balletto',
        'balletti',
        'ballet',
        'coreograf*',
        'tanztheater',
        'flamenco',
        'circuito danza',
        'schiaccianoci',
        'lago dei cigni',
      ],
      short: [
        'danza',
        'danze',
        'danzatori',
        'danzatrici',
        'balletto',
        'coreografia',
        'coreografo',
        'coreografa',
        'tanztheater',
        'flamenco',
      ],
    },
    {
      id: 'stand-up',
      head: ['stand up', 'cabaret', 'one man show', 'one woman show', 'comicita', 'cabarettista', 'comedy'],
      short: [
        'stand up',
        'cabaret',
        'one man show',
        'one woman show',
        'comicita',
        'cabarettista',
        'comedian',
        'ventriloquia',
      ],
    },
    {
      id: 'prosa',
      head: [
        'prosa',
        'commedia',
        'commedie',
        'filodrammatica',
        'filodrammatiche',
        'compagnia teatrale',
        'monologo',
        'tragedia',
        'dramma',
        'atto unico',
        'shakespeare',
        'pirandello',
        'goldoni',
        'spettacolo teatrale',
        'teatro dialettale',
        'schauspiel',
        'theaterstuck',
      ],
      short: [
        'stagione di prosa',
        'commedia',
        'commedie',
        'filodrammatica',
        'filodrammatiche',
        'compagnia teatrale',
        'monologo',
        'tragedia',
        'dramma',
        'drammaturgia',
        'atto unico',
        'spettacolo teatrale',
        'teatro dialettale',
        'teatro d autore',
        'teatro civile',
        'teatro di narrazione',
        'testo e regia',
        'pirandello',
        'shakespeare',
        'goldoni',
        'gruppo teatrale',
        'teatro stabile',
        'brecht',
        'molière',
        'cechov',
        'beckett',
        'ibsen',
        'drammaturgia e regia',
        'schauspiel',
        'theaterstuck',
      ],
    },
  ],
  concerts: [
    {
      id: 'elettronica',
      head: [
        'elettronic*',
        'electronic*',
        'dj',
        'dj set',
        'techno',
        'house music',
        'electro',
        'rave',
        'afterhours',
        'edm',
      ],
      short: ['elettronic*', 'electronic*', 'dj set', 'techno', 'house music', 'electro', 'rave', 'edm'],
    },
    {
      id: 'jazz-blues',
      head: ['jazz', 'blues', 'swing', 'bebop', 'bossa nova', 'big band'],
      short: ['jazz', 'blues', 'swing', 'bebop', 'bossa nova', 'big band'],
    },
    {
      id: 'classica',
      head: [
        'classica',
        'sinfonic*',
        'symphon*',
        'sinfonia',
        'orchestra',
        'filarmonic*',
        'quartetto d archi',
        'sonata',
        'musica da camera',
        'cameristic*',
        'clavicembalo',
        'pianoforte',
        'pianista',
        'violino',
        'violoncello',
        'organo',
        'organi',
        'organistic*',
        'oratorio',
        'requiem',
        'barocc*',
        'recital',
        'conservatorio',
        'musica antica',
        'musicantica',
        'lirica',
        'candlelight',
        'concertistica',
        'mozart',
        'bach',
        'beethoven',
        'vivaldi',
        'haydn',
        'schubert',
        'brahms',
        'liszt',
        'chopin',
        'debussy',
        'wagner',
        'verdi',
        'puccini',
        'rossini',
        'donizetti',
      ],
      short: [
        'musica classica',
        'sinfonic*',
        'symphon*',
        'sinfonia',
        'orchestra',
        'quartetto d archi',
        'musica da camera',
        'cameristic*',
        'clavicembalo',
        'pianoforte',
        'violino',
        'violoncello',
        'oratorio',
        'requiem',
        'musica antica',
        'barocc*',
        'programma',
        'mozart',
        'bach',
        'beethoven',
        'vivaldi',
        'haydn',
        'schubert',
        'brahms',
        'liszt',
        'chopin',
        'debussy',
        'wagner',
        'verdi',
        'puccini',
        'rossini',
        'donizetti',
      ],
    },
    {
      id: 'folk-cori',
      head: [
        'coro',
        'cori',
        'corale',
        'corali',
        'coralita',
        'cantori',
        'gruppo vocale',
        'folk',
        'folklor*',
        'musica popolare',
        'etnic*',
        'world music',
        'klezmer',
        'tarantella',
        'canti popolari',
        'balcanic*',
        'celtic*',
        'irlandes*',
        'banda',
        'fanfara',
        'gospel',
        'chor',
        'volksmusik',
        'blasmusik',
        'musikkapelle',
      ],
      short: [
        'coro',
        'cori',
        'corale',
        'corali',
        'cantori',
        'gruppo vocale',
        'folk',
        'folklor*',
        'musica popolare',
        'world music',
        'klezmer',
        'canti popolari',
        'canti della tradizione',
        'banda musicale',
        'fanfara',
        'gospel',
      ],
    },
    {
      id: 'rock-pop',
      head: [
        'rock',
        'pop',
        'punk',
        'metal',
        'indie',
        'hip hop',
        'rap',
        'trap',
        'cantautor*',
        'reggae',
        'funk',
        'grunge',
        'hardcore',
        'tribute band',
        'cover band',
      ],
      short: [
        'rock',
        'pop',
        'punk',
        'metal',
        'indie',
        'hip hop',
        'rap',
        'cantautor*',
        'reggae',
        'funk',
        'grunge',
        'hardcore',
        'tribute band',
        'cover band',
      ],
      unless: ['pop art', 'pop up', 'popup', 'rock climbing', 'arrampicata'],
    },
  ],
  exhibitions: [
    {
      id: 'fotografia',
      head: ['fotograf*', 'foto', 'photo*', 'scatti', 'nell obiettivo di', 'reportage', 'fotoreporter'],
      short: ['fotograf*', 'foto', 'photo*', 'scatti', 'nell obiettivo di', 'reportage'],
    },
    {
      id: 'scienza',
      head: [
        'scienza',
        'scienze',
        'scientific*',
        'naturalistic*',
        'biodiversita',
        'astronom*',
        'geolog*',
        'fossili',
        'dinosauri',
        'ecolog*',
        'clima',
        'climatic*',
        'tecnologia',
        'tecnologie',
        'robot',
        'planetario',
        'fisica',
        'chimica',
        'biologia',
      ],
      short: [
        'scienza',
        'scienze',
        'scientific*',
        'naturalistic*',
        'biodiversita',
        'astronom*',
        'geolog*',
        'fossili',
        'dinosauri',
        'ecolog*',
        'cambiamento climatico',
        'tecnologia',
        'tecnologie',
        'robot',
        'planetario',
        'fisica',
        'chimica',
        'biologia',
      ],
      sources: ['muse'],
    },
    {
      id: 'storia',
      head: [
        'storia',
        'storico',
        'storica',
        'storici',
        'storiche',
        'archeolog*',
        'romana',
        'romano',
        'medievale',
        'medioevo',
        'rinascimento',
        'guerra',
        'profughi',
        'egizi',
        'egitto',
        'reperti',
        'preistoria',
        'etnografic*',
        'garibaldin*',
        'risorgimento',
        'asburgic*',
        'dopoguerra',
        'resistenza',
        'fascismo',
        'tridentum',
        'trento romana',
        'numismatic*',
      ],
      short: [
        'storia',
        'storico',
        'storica',
        'storici',
        'storiche',
        'archeolog*',
        'medievale',
        'medioevo',
        'rinascimento',
        'prima guerra mondiale',
        'grande guerra',
        'seconda guerra mondiale',
        'profughi',
        'reperti',
        'preistoria',
        'etnografic*',
        'risorgimento',
        'asburgic*',
        'dopoguerra',
        'resistenza',
        'fascismo',
        'tridentum',
        'trento romana',
        'numismatic*',
      ],
    },
    {
      id: 'arte',
      head: [
        'arte',
        'arti',
        'artista',
        'artisti',
        'artistic*',
        'pittura',
        'pittore',
        'pittrice',
        'pittorica',
        'dipinti',
        'scultur*',
        'scultore',
        'personale di',
        'installazione',
        'installazioni',
        'affreschi',
        'ceramic*',
        'incisioni',
        'acquerelli',
        'galleria',
        'kunst',
        'avanguardia',
        'futurismo',
        'futurista',
        'impressionis*',
        'barocco',
        'monografica',
        'antologica',
        'ritratti',
        'stampe',
        'illustrazioni',
        'opere',
      ],
      short: [
        'arte',
        'artista',
        'artisti',
        'artistic*',
        'pittura',
        'pittore',
        'pittrice',
        'dipinti',
        'scultur*',
        'scultore',
        'installazione',
        'installazioni',
        'affreschi',
        'incisioni',
        'acquerelli',
        'avanguardia',
        'futurismo',
        'impressionis*',
        'barocco',
        'monografica',
        'antologica',
        'ritratti',
        'stampe',
        'opere',
        'kunst',
      ],
      unless: ['regola d arte'],
      sources: ['mart'],
    },
  ],
  talks: [
    {
      id: 'libri',
      head: [
        'libro',
        'libri',
        'romanzo',
        'romanzi',
        'scrittore',
        'scrittrice',
        'incontro con l autore',
        'incontro con l autrice',
        'poesia',
        'poesie',
        'poeta',
        'poetessa',
        'lettura',
        'letture',
        'gruppo di lettura',
        'book club',
        'saggio',
        'narrativa',
        'buch',
        'lesung',
        'nuovo volume',
      ],
      short: [
        'libro',
        'libri',
        'romanzo',
        'romanzi',
        'scrittore',
        'scrittrice',
        'incontro con l autore',
        'incontro con l autrice',
        'poesia',
        'poesie',
        'poeta',
        'poetessa',
        'lettura',
        'letture',
        'gruppo di lettura',
        'book club',
        'saggio',
        'narrativa',
        'buch',
        'lesung',
        'nuovo volume',
      ],
      sources: ['arcadia'],
    },
    {
      id: 'dibattiti',
      head: [
        'dibattito',
        'dibattiti',
        'tavola rotonda',
        'panel',
        'discussione',
        'conversazione pubblica',
        'forum',
        'assemblea pubblica',
        'diskussion*',
        'podiumsdiskussion',
        'caffe filosofico',
        'caffe scientifico',
      ],
      short: [
        'dibattito',
        'dibattiti',
        'tavola rotonda',
        'panel',
        'conversazione pubblica',
        'assemblea pubblica',
        'diskussion*',
        'podiumsdiskussion',
      ],
    },
    {
      id: 'conferenze',
      head: [
        'conferenza',
        'conferenze',
        'convegno',
        'seminario',
        'seminari',
        'lezione',
        'lezioni',
        'lectio',
        'simposio',
        'symposium',
        'talk',
        'keynote',
        'webinar',
        'kongress',
        'vortrag',
        'universita popolare',
        'ciclo di incontri',
      ],
      short: [
        'conferenza',
        'conferenze',
        'convegno',
        'seminario',
        'seminari',
        'lezione',
        'lezioni',
        'lectio',
        'simposio',
        'symposium',
        'talk',
        'keynote',
        'webinar',
        'kongress',
        'vortrag',
        'ciclo di incontri',
        'ciclo di conferenze',
      ],
    },
  ],
}

/** Season / festival programmes ('Stagione 2026/2027', 'Prestagione', 'Rassegna'). */
const SEASON = /(?:^| )(?:pre)?stagion[ei]|(?:^| )rassegna(?= |$)/

const compileAll = (words: string[] | undefined) => (words ?? []).map(compile)
const COMPILED = new Map(
  Object.entries(RULES).map(([category, rules]) => [
    category,
    (rules ?? []).map((r) => ({
      id: r.id,
      kids: r.kids ?? false,
      head: compileAll(r.head),
      short: compileAll(r.short),
      unless: compileAll(r.unless),
      sources: r.sources ?? [],
    })),
  ]),
)

/**
 * The subcategory of an event, or undefined: only for the categories of
 * SUBCATEGORIES, and only when a rule recognises it. Pure, so it can be
 * re-run on records carried over from an older events.json.
 */
export function subcategoryOf(
  e: Pick<Event, 'category' | 'title' | 'summary' | 'tags' | 'source'> & { sources?: string[] },
): string | undefined {
  const rules = COMPILED.get(e.category)
  if (!rules) return undefined
  const head = hayOf([e.title])
  const short = hayOf([e.title, e.summary])
  const ok = (r: (typeof rules)[number]) => !r.unless.some((p) => p.test(short))
  const hit = (words: RegExp[], hay: string) => words.some((p) => p.test(hay))
  const tagged = (r: (typeof rules)[number]) => r.kids && e.tags.includes('kids')
  const byTitle = rules.find((r) => ok(r) && hit(r.head, head))?.id
  // "Teatro di Rovereto | Stagione 2026/2027": a season lists every genre in
  // its blurb, so only its own title can classify it.
  if (!byTitle && SEASON.test(head)) return undefined
  return (
    rules.find((r) => ok(r) && tagged(r))?.id ??
    byTitle ??
    rules.find((r) => ok(r) && hit(r.short, short))?.id ??
    rules.find((r) => r.sources.includes(e.source) || r.sources.some((s) => e.sources?.includes(s)))?.id
  )
}

/** The event with `subcategory` set (or removed when no rule recognises it). */
export function withSubcategory(e: Event): Event {
  const { subcategory: _old, ...rest } = e
  const sub = subcategoryOf(e)
  return sub ? { ...rest, subcategory: sub } : rest
}
